###

################################################################################
# subscribe to ./main_endless_conditional.py
################################################################################
GET http://localhost:8000/endless
Accept: application/json

###

################################################################################
# Test examples/stream_generator.py
################################################################################
# Push messages for stream_generator.py
# curl -X 'POST'
#  'http://127.0.0.1:8000/message?message=xxx'
#  -H 'accept: application/json'
#  -d ''
POST http://127.0.0.1:8000/message?message=xxx
accept: application/json
Content-Type: application/x-www-form-urlencoded

###

# subscribe to sse endpoint to view the sent messages
GET http://localhost:8000/sse
Accept: application/json

###
